<div id="view-content">
<?php 
	$this->title = "Add new User";
	$this->headTitle($this->title);
	$str="$this->bodyTag";
	echo $this->form;
//	echo "<$this->errorMsg;
	$jsFile    ='/zf-tutorial/application/views/scripts/usersmanagement/validateAddUserForm.js';
	$jqueryLib ='/zf-tutorial/library/JSLib/jquery-1.8.0.js';
	$this->headScript()->appendFile($jqueryLib);//JQUERY library
	$this->headScript()->appendFile($jsFile);//java script to filter errors
 
	?>
	<br>
	<p id="errMsg">  </p>
</div>
