<
	
<?php
$this->title = "Delete user";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete user: 
'<?php echo $this->escape($this->user['username']); ?>'? 

</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" /> // trasefer hidden parameter to page - id
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
</div>