<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - '); 
$this->headTitle('Video Control Center');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
<?php echo $this->headScript(); // embedding Java script ?> 
<?php
/* 
if (!is_null($this->bodyTag('onload', 'donothing()') )){
	$bodyTag=$this->bodyTag('onload', 'donothing()');
	$bodyStr=$this->bodyTag()->toString(Pro_View_Helper_BodyTag::CLOSE) . PHP_EOL;
	echo "$this->bodyTag() . PHP_EOL";
}else
{
	echo'<head> <br>';
}

*/
		
?>
</head>
<body>
<div id="content">
<h1><?php echo $this->escape($this->title); ?></h1>
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>
