<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - '); 
$this->headTitle('Video Control Center');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
echo $this->headMeta();
echo $this->headTitle(); 
$tmp=$this->baseUrl().'/css/style .css';
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css?'.date('l jS \of F Y h:i:s A')); // adding date to enforce css cache clear
echo $this->headScript(); // embedding Java script 
?> 
</head>

<body>
<div id="outer">
<div id="header" align="center"><?php echo $this->escape($this->title); ?>
<?php 
$username=$this->escape($this->layout()->username);
$userRole=$this->escape($this->layout()->role);
$contentHeader=$this->escape($this->layout()->header);
?>
<table class="headerTable" style="float:left;">
<tr>
	<td>User name:</td>
	<td><?php echo "$username";?></td>
</tr>
<tr>
	<td>Role:</td>
	<td><?php echo "$userRole";?></td>
</tr>
</table>

<?php
if ($username!=null)
{
	$loginUrl=$this->url(array('controller'=>'authentication','action'=>'logout'));
	?>
	<!--  confirm logout -->
	 <a href=<?php echo $loginUrl;?>><button id='logoutBtn' 
 								  onClick="return confirm('Are you sure you want to logout?')">Logout</button></a>
<?php 
} ?>
<h1> <?php echo APPLICATION_TITLE;?></h1>
</div> 
<div id="bar"></div>
<div id="bodyblock" align="right">
<div id="column" align="left">
<h4 align="center">Menu</h4>
<?php echo $this->navigation();?>
</div>
<div id="content">
<?php 
$controllerName =$this->escape($this->layout()->controller);
$actionName=$this->escape($this->layout()->action);
$contentHeader=$this->escape($this->layout()->contentHeader);
require_once(APPLICATION_PATH.'/configs/contentHeader.php');
//echo "$controllerName  $actionName";
$header=$contentHeader[strtolower($controllerName)][strtolower($actionName)];
?>
<!-- hidden fields - controller and action -->
<form method='post'>
<input type="hidden" name="sourceController" value="<?php echo "$controllerName"; ?>"></input>
<input type="hidden" name="sourceAction" value="<?php echo "$actionName"; ?>"></input>
</form>
<h3 align="center"><?php echo "$header"; ?></h3>
<?php echo $this->layout()->content;?>
</div>
<div id="footer" align="center"></div>
</div>
</div>
</body>
</html>
