<div id="view-content">
<?php 
	$this->title = "Add\Update Video Source";
	$this->headTitle($this->title);
	$str="$this->bodyTag";//??
	echo $this->form;

	$jsFile    ='/zf-tutorial/application/views/scripts/config/validateAddVideoSourceForm.js';
	$jqueryLib ='/zf-tutorial/library/JSLib/jquery-1.8.0.js';
	$this->headScript()->appendFile($jqueryLib);//JQUERY library
	$this->headScript()->appendFile($jsFile);//java script to filter errors

	?>
	<br>
	<p id="errMsg"> <?php echo $this->errorMsg?>  </p>
</div>
