<?php
$this->title = "Video sources";
$this->headTitle($this->title);
?>
<div id='videoSourceTable'>
<table>
<tr>
<th>Name</th>
<th>Description</th>
<th>IP address</th>
<th>frames per second</th>
<th>MBR</th>
</tr>
<?php foreach($this->videoSources as $source) : ?>
<tr>
<td><?php echo $this->escape($source['name']);?></td>
<td><?php echo $this->escape($source['description']);?></td>
<td><?php echo $this->escape($source['encoder_IP']);?></td>
<td><?php echo $this->escape($source['encoder_fps']);?></td>
<td><?php echo $this->escape($source['encoder_MBR']);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'Config',
'action'=>'deleteSource', 'id'=>$source['id']));?>" onClick=
          "return confirm('Are you sure you want to delete source <?php echo $source['name'];?>?')">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
</div>
<p><a href="<?php echo $this->url(array('controller'=>'Config',
'action'=>'addsource'));?>">Add Video Source</a></p>
